* IAC Project for Linode VPS

** Terraform

We use terraform to start up a Linode VPS. So this project assumes that Terraform is installed in your system.
The instructions are available here: [[https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli#install-terraform]]
I am using for this example the smallest vps with shared CPU available on Linode.

*** Terraform provides in use

[[https://registry.terraform.io/providers/linode/linode/latest]] Linode Provider

** Linode API Token

We need an API_TOKEN to run this project. The token needs the following permissions:

1. Linodes (Read/Write)
2. Events (Read/Write)
3. Domains (Read/Write)

** SSH Key

In order to access the server, we make use of an SSH key, which needs to be generated in your local prior to running
terraform.

To generate the key use the following command. Ensure to save the file under: =~/.ssh/id_linode_ed25519=.

#+begin_src
ssh-keygen -t ed25519
#+end_src
* Run the project

** Terraform init

The first time that this project is run on your machine is necessary to run:

#+begin_src sh
terraform init
#+end_src

** Environment variables

There is an =.terraform.tfvars.example= file.
Duplicate the file to be named =.env= and replace the values with your own.

** Terraform plan

To see what is going to be created run the command:

#+begin_src sh
terraform plan
#+end_src

** Terraform apply

To create the instance on Linode, run the =apply= command:

#+begin_src sh
terraform apply
#+end_src

** Terraform Destroy

When you are done with your machine, just run =destroy= to delete the resources that are no longer required.

#+begin_src
terraform destroy
#+end_src

* Access the server

Once the server has been created, also an SSH key has been uploaded and can be used to access the server.

#+begin_src sh
ssh -i ~/.ssh/id_linode_ed25519 root@178.79.154.54
#+end_src
